name: Build

on: push

jobs:
  build:
    runs-on: windows 10

    steps:
      - uses: actions/checkout@v2

      
      - name: Build application
        run: make

      - name: Test application
        run: make test

      