name: Build

on: push

jobs:
  build:
    runs-on: windows 10

    steps:
      - uses: actions/checkout@v2
      - name: Check codestyle
        run: git ls-files *.{c,h}

      
      - name: Build application
        run: make

      - name: Test application
        run: make test

      