name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:  
      - uses: actions/checkout@v2    
      
      - name: download libs
        run:
          sudo apt -y install python3-pip
      - name: lib1 
        run: 
          pip install --target libs openpyxl
      - name: lib2
        run: 
          sudo pip3 install --target libs --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
      - name: path
        run:
          export PATH=$PATH:libs

            
      - name: Build application
        run: 
          make 
          

