name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
            
      - name: Build application
        run:  
<<<<<<< HEAD
          python -m pip install --upgrade pip
          
=======
          python src/main.py
>>>>>>> 4589b657818fa4f1dba9728269e002f892889200
