name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:  
      - uses: actions/checkout@v2    
      - name: download libs
        run:
          sudo apt-get install python3
      - name: download python
        run:
          sudo apt -y install python3-pip
          
      - name: download requests
        run:
          sudo pip3 install requests
          
      - name: lib1 
        run: 
          pip install openpyxl
      - name: lib2
        run: 
          pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
      - name: path
        run:
          export PATH=$PATH:libs

            
      - name: Build application
        run: 
          make 
          

